name: N-ElytraProtection
version: '${project.version}'
main: xyz.najlek.elytraprotection.Bootstrap
api-version: 1.19
author: Najlek
description: simple plugin to protect elytra
website: https://www.najlek.pl
commands:
  elytra:
    description: Manage elytra